# Generated by Django 5.2.4 on 2025-07-12 12:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_otp_verification_user_register_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
