# Generated by Django 5.2.4 on 2025-08-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_first_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
