# Generated by Django 5.2.4 on 2025-09-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_referralcode_user_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_types',
        ),
    ]
