# Generated by Django 5.2.4 on 2025-10-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_user_created_at_user_subscription_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='referral_code_used',
        ),
        migrations.AddField(
            model_name='referralcode',
            name='discount_percentage',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
