# Generated by Django 5.2.4 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_rename_verified_user_referral_code_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=128)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_key',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
