# Generated by Django 5.2.4 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailoutbox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
