# Generated by Django 5.2.4 on 2025-09-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
