# Generated by Django 5.2.4 on 2025-09-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_alter_register_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
