# Generated by Django 5.2.4 on 2025-09-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_alter_register_description_alter_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='description',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
