# Generated by Django 5.2.4 on 2025-10-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_alter_register_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
