# Generated by Django 5.2.4 on 2025-11-14 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0005_alter_register_options_alter_register_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['user', 'name'], name='register_user_name_idx'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['user', 'debit'], name='register_user_debit_idx'),
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['user', 'credit'], name='register_user_credit_idx'),
        ),
        migrations.AddConstraint(
            model_name='register',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_register_name'),
        ),
    ]
