# Generated by Django 5.2.4 on 2025-07-10 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_to_bo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_to_so', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ssy', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('td', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ippb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
