# Generated by Django 5.2.4 on 2025-07-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='cash_to_bo',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='cash_to_so',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='ippb',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='net_balance',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='rd',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='ssy',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='td',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='total_debit',
        ),
    ]
