# Generated by Django 5.2.4 on 2025-11-14 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_journal_cash_to_bo_remove_journal_cash_to_so_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['user', 'date'], name='journal_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['user', 'is_holiday'], name='journal_user_holiday_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['date'], name='journal_date_idx'),
        ),
    ]
