# Generated by Django 5.2.4 on 2025-07-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='register',
            field=models.CharField(choices=[('cash to bo', 'Cash to BO'), ('cash to so', 'Cash to SO'), ('ssy', 'SSY'), ('td', 'TD'), ('rd', 'RD'), ('ippb', 'IPPB')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=50),
        ),
    ]
