# Generated by Django 5.2.4 on 2025-07-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='register',
            field=models.CharField(max_length=100),
        ),
    ]
