# Generated by Django 5.2.4 on 2025-08-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image_keys',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
