# Generated by Django 5.2.4 on 2025-09-30 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_alter_register_description'),
        ('transactions', '0004_transaction_image_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.register'),
        ),
    ]
