# Generated by Django 5.2.4 on 2025-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='register',
            field=models.CharField(max_length=100),
        ),
    ]
