# Generated by Django 5.2.4 on 2025-12-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
