# Generated by Django 5.2.4 on 2025-12-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_plan_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limited',
            field=models.BooleanField(default=False),
        ),
    ]
